  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build (Standard)
        shell: cmd
        run: |
          cd build
          cmake -G "Visual Studio 16 2019" -DBUILD_SDLGPU=On -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_WITH_ALL=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..
          cmake --build . --config MinSizeRel --parallel
      - name: Upload Standard Build
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-windows-standard"
          path: |
            build/bin/tic80.exe
            build/bin/*.dll

      - name: Build Pro
        shell: cmd
        run: |
          cd build
          cmake -G "Visual Studio 16 2019" -DBUILD_SDLGPU=On -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_PRO=On -DBUILD_WITH_ALL=ON ..
          cmake --build . --config MinSizeRel --parallel
      - name: Upload Pro Build
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-windows-pro"
          path: |
            build/bin/tic80.exe
            build/bin/*.dll
